/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author charlie
 */
public class frmCalculadora extends javax.swing.JFrame {
    
    private boolean punto=true; //Sirve para el botón de punto decimal
    String valor1,valor2, signo, contenido;
    Double resultado;
    /**
     * Creates new form frmCalculadora
     */
    public frmCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtmostrar = new javax.swing.JTextField();
        btnmasmenos = new javax.swing.JButton();
        btnraiz = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn1x = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnx2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnxy = new javax.swing.JButton();
        btnresta = new javax.swing.JButton();
        btnpunto = new javax.swing.JButton();
        btnsuma = new javax.swing.JButton();
        btnc = new javax.swing.JButton();
        btnex = new javax.swing.JButton();
        btnigual = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        btnmultiplicar = new javax.swing.JButton();
        btndivision = new javax.swing.JButton();
        btnex1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtmostrar.setFont(new java.awt.Font("Mukta", 1, 24)); // NOI18N
        getContentPane().add(txtmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 50));

        btnmasmenos.setBackground(new java.awt.Color(102, 153, 255));
        btnmasmenos.setFont(new java.awt.Font("Mukta", 1, 24)); // NOI18N
        btnmasmenos.setText("+ -");
        btnmasmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasmenosActionPerformed(evt);
            }
        });
        getContentPane().add(btnmasmenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 80, 80));

        btnraiz.setBackground(new java.awt.Color(102, 153, 255));
        btnraiz.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btnraiz.setText("Raíz");
        btnraiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnraizActionPerformed(evt);
            }
        });
        getContentPane().add(btnraiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 80));

        btn7.setBackground(new java.awt.Color(102, 153, 255));
        btn7.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, 80));

        btn4.setBackground(new java.awt.Color(102, 153, 255));
        btn4.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 80, 80));

        btn1.setBackground(new java.awt.Color(102, 153, 255));
        btn1.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 80, 80));

        btn0.setBackground(new java.awt.Color(102, 153, 255));
        btn0.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 160, 80));

        btn1x.setBackground(new java.awt.Color(102, 153, 255));
        btn1x.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btn1x.setText("1/x");
        btn1x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1xActionPerformed(evt);
            }
        });
        getContentPane().add(btn1x, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 80, 80));

        btn8.setBackground(new java.awt.Color(102, 153, 255));
        btn8.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 80, 80));

        btn5.setBackground(new java.awt.Color(102, 153, 255));
        btn5.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 80, 80));

        btn2.setBackground(new java.awt.Color(102, 153, 255));
        btn2.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 80, 80));

        btn6.setBackground(new java.awt.Color(102, 153, 255));
        btn6.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 80, 80));

        btnx2.setBackground(new java.awt.Color(102, 153, 255));
        btnx2.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btnx2.setText("x^2");
        btnx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 80, 80));

        btn3.setBackground(new java.awt.Color(102, 153, 255));
        btn3.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 80, 80));

        btn9.setBackground(new java.awt.Color(102, 153, 255));
        btn9.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 80, 80));

        btnxy.setBackground(new java.awt.Color(102, 153, 255));
        btnxy.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btnxy.setText("x^y");
        btnxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxyActionPerformed(evt);
            }
        });
        getContentPane().add(btnxy, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 80, 80));

        btnresta.setBackground(new java.awt.Color(102, 153, 255));
        btnresta.setFont(new java.awt.Font("Mukta", 1, 28)); // NOI18N
        btnresta.setText("-");
        btnresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaActionPerformed(evt);
            }
        });
        getContentPane().add(btnresta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 80, 80));

        btnpunto.setBackground(new java.awt.Color(102, 153, 255));
        btnpunto.setFont(new java.awt.Font("Mukta", 1, 24)); // NOI18N
        btnpunto.setText(".");
        btnpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpuntoActionPerformed(evt);
            }
        });
        getContentPane().add(btnpunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 80, 80));

        btnsuma.setBackground(new java.awt.Color(102, 153, 255));
        btnsuma.setFont(new java.awt.Font("Mukta", 1, 24)); // NOI18N
        btnsuma.setText("+");
        btnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumaActionPerformed(evt);
            }
        });
        getContentPane().add(btnsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 80, 160));

        btnc.setBackground(new java.awt.Color(102, 153, 255));
        btnc.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btnc.setText("C");
        btnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncActionPerformed(evt);
            }
        });
        getContentPane().add(btnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 80, 240));

        btnex.setBackground(new java.awt.Color(102, 153, 255));
        btnex.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btnex.setText("e^x");
        btnex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexActionPerformed(evt);
            }
        });
        getContentPane().add(btnex, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 80, 80));

        btnigual.setBackground(new java.awt.Color(102, 153, 255));
        btnigual.setFont(new java.awt.Font("Mukta", 1, 24)); // NOI18N
        btnigual.setText("=");
        btnigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnigualActionPerformed(evt);
            }
        });
        getContentPane().add(btnigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 80, 80));

        btnborrar.setBackground(new java.awt.Color(102, 153, 255));
        btnborrar.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btnborrar.setText("<----");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 160, 80));

        btnmultiplicar.setBackground(new java.awt.Color(102, 153, 255));
        btnmultiplicar.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btnmultiplicar.setText("X");
        btnmultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnmultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 80, 80));

        btndivision.setBackground(new java.awt.Color(102, 153, 255));
        btndivision.setFont(new java.awt.Font("Mukta", 1, 24)); // NOI18N
        btndivision.setText("/");
        btndivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivisionActionPerformed(evt);
            }
        });
        getContentPane().add(btndivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 80, 80));

        btnex1.setBackground(new java.awt.Color(102, 153, 255));
        btnex1.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        btnex1.setText("e^x");
        btnex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnex1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 80, 80));

        jButton1.setFont(new java.awt.Font("Mukta", 1, 18)); // NOI18N
        jButton1.setText("XD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 80, 80));

        getAccessibleContext().setAccessibleName("Calculadora");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1xActionPerformed
        //EVENTO PARA BOTON 1X
        contenido=txtmostrar.getText();
        if(contenido.length()>0){
            resultado= 1/(Double.parseDouble(contenido));
            txtmostrar.setText(resultado.toString());
        }
    }//GEN-LAST:event_btn1xActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // Dando Valor al Botón 0
        txtmostrar.setText("");
        txtmostrar.setText(txtmostrar.getText()+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // Dando Valor al Botón 1
        txtmostrar.setText("");
        txtmostrar.setText(txtmostrar.getText()+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // Dando Valor al Botón 2
        txtmostrar.setText("");
        txtmostrar.setText(txtmostrar.getText()+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // Dando Valor al Botón 3
        txtmostrar.setText("");
        txtmostrar.setText(txtmostrar.getText()+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // Dando Valor al Botón 4
        txtmostrar.setText("");
        txtmostrar.setText(txtmostrar.getText()+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // Dando Valor al Botón 5
        txtmostrar.setText("");
        txtmostrar.setText(txtmostrar.getText()+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // Dando Valor al Botón 6
        txtmostrar.setText("");
        txtmostrar.setText(txtmostrar.getText()+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // Dando Valor al Botón 7
        txtmostrar.setText("");
        txtmostrar.setText(txtmostrar.getText()+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // Dando Valor al Botón 8
        txtmostrar.setText("");
        txtmostrar.setText(txtmostrar.getText()+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // Dando Valor al Botón 9
        txtmostrar.setText("");
        txtmostrar.setText(txtmostrar.getText()+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActionPerformed
        // Dando Valor al Botón C
        txtmostrar.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_btncActionPerformed

    private void btnpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpuntoActionPerformed
        // BTNPUNTO handling code here:
        contenido=txtmostrar.getText();
        //contenido menos o igual a 0, muestra "0."
        //si el campo está vacío, muestra "0."
        if(contenido.length() <= 0){
            txtmostrar.setText("0.");
        }else
            //Sí ya existe un punto no podrá colocarse otro
            if(txtmostrar.getText().contains(".")){
            }else {
                txtmostrar.setText(txtmostrar.getText()+".");
                punto=false;
            }
    }//GEN-LAST:event_btnpuntoActionPerformed
    //LÓGICA DE OPERACIONES DE LA CALCULADORA     
    public static String operaciones(String valor1, String valor2, String signo){
            Double resultadocalc=0.0;
            String respuesta;
            //SUMA
            if(signo.equals("+")){
                resultadocalc=Double.parseDouble(valor1)+Double.parseDouble(valor2);
            } 
            //RESTA
            else if(signo.equals("-")){
                resultadocalc=Double.parseDouble(valor1)-Double.parseDouble(valor2);
            } 
            //MULTIPLICACIÓN
            else if(signo.equals("*")){
                resultadocalc=(Double.parseDouble(valor1))*(Double.parseDouble(valor2));
            }
            //DIVISIÓN
            else if(signo.equals("/")){
                resultadocalc=Double.parseDouble(valor1)/Double.parseDouble(valor2);
            }
            //POTENCIA
            else if(signo.equals("x^y")){
                resultadocalc=Math.pow(Double.parseDouble(valor1), Double.parseDouble(valor2));
            }
            respuesta=resultadocalc.toString();
            return respuesta;
     }
    
    private void btnmasmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasmenosActionPerformed
        // EVENTO PARA MÁS-MENOS
        contenido=txtmostrar.getText();
        //Se multiplicara el resultado por -1 para obtener resultado negativo
        if(contenido.length()>0){
            resultado=(-1)*Double.parseDouble(contenido);
            txtmostrar.setText(resultado.toString());
        }
    }//GEN-LAST:event_btnmasmenosActionPerformed

    private void btnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumaActionPerformed
        // EVENTOPARA SUMA:
        if(!txtmostrar.getText().equals("")){
            valor1=txtmostrar.getText();
            //estableciendo la relación del signo usada en la lógica de operaciones:
            signo="+";
            txtmostrar.setText(signo);
        }
    }//GEN-LAST:event_btnsumaActionPerformed

    private void btnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaActionPerformed
        //EVENTO PARA RESTA
        if(!txtmostrar.getText().equals("")){
            valor1=txtmostrar.getText();
            //estableciendo la relación del signo usada en la lógica de operaciones:
            signo="-";
            txtmostrar.setText(signo);
    }//GEN-LAST:event_btnrestaActionPerformed
    }
    private void btnmultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplicarActionPerformed
        //EVENTO PARA MULTIPLICAR
        if(!txtmostrar.getText().equals("")){
            valor1=txtmostrar.getText();
            //estableciendo la relación del signo usada en la lógica de operaciones:
            signo="*";
            txtmostrar.setText("x");
    }//GEN-LAST:event_btnmultiplicarActionPerformed
    }
    private void btndivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivisionActionPerformed
        //EVENTO PARA DIVIDIR
        if(!txtmostrar.getText().equals("")){
            valor1=txtmostrar.getText();
            //estableciendo la relación del signo usada en la lógica de operaciones:
            signo="/";
            txtmostrar.setText(signo);
    }//GEN-LAST:event_btndivisionActionPerformed
    }
    
    private void btnxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxyActionPerformed
           //EVENTO PARA POTENCIA
        if(!txtmostrar.getText().equals("")){
            valor1=txtmostrar.getText();
            //estableciendo la relación del signo usada en la lógica de operaciones:
            signo="x^y";
            txtmostrar.setText("^");
    }
    }//GEN-LAST:event_btnxyActionPerformed

    private void btnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnigualActionPerformed
        // EVENTO PARA = Y MOSTRAR RESULTAD DE OPERACIONES
        String resultadototal;
        valor2=txtmostrar.getText();
        if(!valor2.equals("")){
            resultadototal=operaciones(valor1,valor2,signo);
            txtmostrar.setText(resultadototal);
        }
    }//GEN-LAST:event_btnigualActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        // EVENTO DEL BOTON PARA BORRAR:
        contenido=txtmostrar.getText();
        if(contenido.length()>0){
            contenido=contenido.substring(0, contenido.length()-1);
            txtmostrar.setText(contenido);
        }
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnraizActionPerformed
        // EVENTO BOTON RAÍZ
        contenido=txtmostrar.getText();
        if(contenido.length()>0){
            resultado=Math.sqrt(Double.parseDouble(contenido));
            txtmostrar.setText(resultado.toString());
        }
    }//GEN-LAST:event_btnraizActionPerformed

    private void btnx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnx2ActionPerformed
        // EVENTO PARA BOTON X2
        contenido=txtmostrar.getText();
        if(contenido.length()>0){
            resultado=Math.pow(Double.parseDouble(contenido),2);
            txtmostrar.setText(resultado.toString());
        }
    }//GEN-LAST:event_btnx2ActionPerformed

    private void btnex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnex1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnex1ActionPerformed

    private void btnexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexActionPerformed
        // EVENTO PARA BOTON ex
        contenido=txtmostrar.getText();
        if(contenido.length()>0){
            resultado=Math.exp(Double.parseDouble(contenido));
            txtmostrar.setText(resultado.toString());
        }
    }//GEN-LAST:event_btnexActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // DANDO VALOR AL BOTON DE CARITA FELIZ
        txtmostrar.setText("");
        txtmostrar.setText(txtmostrar.getText()+"XD");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn1x;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btnc;
    private javax.swing.JButton btndivision;
    private javax.swing.JButton btnex;
    private javax.swing.JButton btnex1;
    private javax.swing.JButton btnigual;
    private javax.swing.JButton btnmasmenos;
    private javax.swing.JButton btnmultiplicar;
    private javax.swing.JButton btnpunto;
    private javax.swing.JButton btnraiz;
    private javax.swing.JButton btnresta;
    private javax.swing.JButton btnsuma;
    private javax.swing.JButton btnx2;
    private javax.swing.JButton btnxy;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField txtmostrar;
    // End of variables declaration//GEN-END:variables
}
